1:
  /system/chassis/motherboard/cpu0:
    entityID: 3
    entityInstance: 1
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Custom Field 2
          IPMIFruSection: Board
          IPMIFruValueDelimiter: 58
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
2:
  /system/chassis/motherboard/cpu1:
    entityID: 3
    entityInstance: 2
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Revision:
        Version:
          IPMIFruProperty: Custom Field 2
          IPMIFruSection: Board
          IPMIFruValueDelimiter: 58
      xyz.openbmc_project.Inventory.Decorator.Asset:
        BuildDate:
          IPMIFruProperty: Mfg Date
          IPMIFruSection: Board
        PartNumber:
          IPMIFruProperty: Part Number
          IPMIFruSection: Board
        Manufacturer:
          IPMIFruProperty: Manufacturer
          IPMIFruSection: Board
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Board
      xyz.openbmc_project.Inventory.Item:
        PrettyName:
          IPMIFruProperty: Name
          IPMIFruSection: Board
3:
  /system/chassis/motherboard:
    entityID: 2
    entityInstance: 3
    interfaces:
#define on 'xyz/openbmc_project/Inventory/FoxconnFruItem.interface.yaml'
#with phosphor-dbus-interfaces.git
      xyz.openbmc_project.Inventory.FoxconnFruItem:
  /system:
    entityID: 0
    entityInstance: 3
    interfaces:
      xyz.openbmc_project.Inventory.Decorator.Asset:
        SerialNumber:
          IPMIFruProperty: Serial Number
          IPMIFruSection: Chassis
        Model:
          IPMIFruProperty: Part Number
          IPMIFruSection: Chassis

